### PR TITLE
update to test autotester

### PR DESCRIPTION
**Pull request by jmox0351**
Erase this information and put your Pull Request comments here
---
Instructions for Issuing a Pull Request to sst-core
---------------------------------------------------

1 - Verify that the Pull Request is targeted to the **devel** branch of sstsimulator/sst-core

2 - Verify that Source branch is up to date with the devel branch of sst-core

3 - After submitting your Pull Request:
   * Automatic Testing will commence in a short while 
      * Pull Requests will be tested with the devel branches of the sst-elements and sst-sqe repositories
         * These branches are syncronized with the devel branch of sst-core.  This is why is it important to keep your source branch up to date.
      * If testing passes, the SST Core developers will review your changes and merge them or contact you for more information
         * Pull Requests from forks will not be automatically tested until the code is inspected.
         * Pull Requests from forks will not be automatically merged into the devel branch.
      * If testing fails, You will be notified of the test results.  
         * The Pull Request will be retested on a regular basis - Changes to the source branch can be made to correct problems
         
----

### CODE REVIEW

**Comment by jmox0351** [comment]
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

**Comment by jmox0351** [comment]
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__X_JCM_AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-core</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: STARTED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 109</li>
  <li>Status: STARTED</li>
</ul>
</table>

## Using Repos:

<dl>
  <dt>Repo: CORE (jmox0351/sst-core)</dt>
  <ul>
    <li>Branch: try1</li>
    <li>SHA: 6f91d6c04d1f33332abcc5be63843799105e6881</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: ELEMENTS (sstsimulator/sst-elements)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 0aa671c2d3bb3f6366be4f9220f445be67c7ccb7</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: MACRO (sstsimulator/sst-macro)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: 680a0029175e1085bb63db0e3c0a098c2eeb78a7</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

<dl>
  <dt>Repo: SQE (sstsimulator/sst-sqe)</dt>
  <ul>
    <li>Branch: devel</li>
    <li>SHA: c3f5ac7ed4cc360e983b8ee009a30477972793ca</li>
    <li>Mode: SUPPORT_REPO</li>
  </ul>
</dl>

Pull Request Author: jmox0351
</details>
</details>

**Comment by jmox0351** [comment]
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: SST__X_JCM_AutotestGen2_NewFW_sst-test_OMPI-4.0.5_PY2.7_sst-core</h3>
<ul>
  <li>Build Num: 1</li>
  <li>Status: PASSED</li>
</ul>
</table>

<h2>Build Information</h2>
<h3>Test Name: SST__AutotestGen2_NewFW_Ubuntu-18.04_OMPI-4.0.5_PY3.6_sst-macro_withsstcore</h3>
<ul>
  <li>Build Num: 109</li>
  <li>Status: PASSED</li>
</ul>
</table>
</details>

**Comment by jmox0351** [comment]
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

**Comment by jmox0351** [comment]
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

**Comment by jmox0351** [comment]
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

**Comment by jcmoxley** [comment]
Leaving a comment. Change abc

**Comment by jmox0351** [comment]
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

**Comment by jcmoxley** [comment]
Pull request autotester appears to be working

**Pull request merged**
